# Curated list of PyPI projects to analyze.
# Sorted by Pct Of Total (import share in fbcode), descending.

projects = [
  { "name" = "numpy", "exclude" = ["numpy/typing/tests/**"] },
  { "name" = "pandas" },
  { "name" = "pandas-stubs" },
  { "name" = "narwhals" },
  { "name" = "scipy-stubs" },
  { "name" = "click" },
  { "name" = "pytest" },
  { "name" = "PyYAML" },
  { "name" = "types-PyYAML" },
  { "name" = "requests" },
  { "name" = "types-requests" },
  { "name" = "six" },
  { "name" = "types-six" },
  { "name" = "pytz" },
  { "name" = "types-pytz" },
  { "name" = "tqdm" },
  { "name" = "types-tqdm" },
  { "name" = "fire" },
  { "name" = "trimesh" },
  { "name" = "Pillow" },
  { "name" = "psutil" },
  { "name" = "types-psutil" },
  { "name" = "jinja2" },
  { "name" = "networkx" },
  { "name" = "types-networkx" },
  { "name" = "mmcv" },
  { "name" = "libcst" },
  { "name" = "imageio" },
  { "name" = "fsspec" },
  { "name" = "aiohttp" },
  { "name" = "h5py" },
  { "name" = "matplotlib" },
  { "name" = "regex" },
  { "name" = "types-regex" },
  { "name" = "transformers" },
  { "name" = "seaborn", "exclude" = ["seaborn/external/**"] },
  { "name" = "types-seaborn" },
  { "name" = "boto3" },
  { "name" = "aiofiles" },
  { "name" = "types-aiofiles" },
  { "name" = "soundfile" },
  { "name" = "munch" },
  { "name" = "msgpack" },
  { "name" = "sqlalchemy" },
  { "name" = "einops" },
  { "name" = "librosa" },
  { "name" = "cloudpickle" },
  { "name" = "jsonpickle" },
  { "name" = "torchmetrics" },
  { "name" = "tabulate" },
  { "name" = "types-tabulate" },
  { "name" = "paramiko" },
  { "name" = "types-paramiko" },
  { "name" = "asyncclick" },
  { "name" = "sympy" },
  { "name" = "joblib" },
  { "name" = "thrift" },
  { "name" = "flatbuffers" },
  { "name" = "decord" },
  { "name" = "wandb", "exclude" = ["wandb/vendor/**"] },
  { "name" = "av" },
  { "name" = "asyncssh" },
  { "name" = "orjson" },
  { "name" = "simpy" },
  { "name" = "sqlparse" },
  { "name" = "ipywidgets" },
  { "name" = "nltk", "exclude" = ["nltk/test/**"] },
  { "name" = "timm" },
  { "name" = "xgboost" },
  { "name" = "coloredlogs" },
  { "name" = "dill" },
  { "name" = "kornia" },
  { "name" = "mercantile" },
  { "name" = "botocore", "exclude" = ["botocore/vendored/**"] },
  { "name" = "urllib3" },
  { "name" = "ipython", "exclude" = ["IPython/external/**", "IPython/testing/**"] },
  { "name" = "ipdb" },
  { "name" = "lmdb" },
  { "name" = "pexpect" },
  { "name" = "types-pexpect" },
  { "name" = "lpips" },
  { "name" = "more-itertools" },
  { "name" = "dash-bootstrap-components" },
  { "name" = "gitpython" },
  { "name" = "shapely" },
  { "name" = "types-shapely" },
  { "name" = "importlib-resources" },
  { "name" = "parameterized" },
  { "name" = "datasets" },
  { "name" = "hypothesis", "exclude" = ["hypothesis/vendor/**"] },
  { "name" = "prettytable" },
  { "name" = "aioitertools" },
  { "name" = "pydot" },
  { "name" = "jsonschema" },
  { "name" = "types-jsonschema" },
  { "name" = "pyzmq" },
  { "name" = "zstandard" },
  { "name" = "sacrebleu" },
  { "name" = "graphviz" },
  { "name" = "simplejson" },
  { "name" = "types-simplejson" },
  { "name" = "colorama" },
  { "name" = "types-colorama" },
  { "name" = "click-log" },
  { "name" = "types-click-log" },
  { "name" = "plotly" },
  { "name" = "spacy" },
  { "name" = "numba", "exclude" = ["numba/cloudpickle/**"] },
  { "name" = "openai" },
  { "name" = "uvloop" },
  { "name" = "streamlit", "exclude" = ["streamlit/vendor/**"] },
  { "name" = "phpserialize" },
  { "name" = "gym" },
  { "name" = "msgspec" },
  { "name" = "commentjson" },
  { "name" = "cachetools" },
  { "name" = "types-cachetools" },
  { "name" = "pint" },
  { "name" = "editdistance" },
  { "name" = "types-editdistance" },
  { "name" = "humanfriendly" },
  { "name" = "rich" },
  { "name" = "openpyxl" },
  { "name" = "types-openpyxl" },
  { "name" = "shap" },
  { "name" = "nest-asyncio" },
  { "name" = "typing-extensions" },
  { "name" = "gradio", "exclude" = ["gradio/test_data/**"] },
  { "name" = "pyjq" },
  { "name" = "oyaml" },
  { "name" = "toolz" },
  { "name" = "yappi" },
  { "name" = "httplib2" },
  { "name" = "types-httplib2" },
  { "name" = "progressbar2" },
  { "name" = "dacite" },
  { "name" = "argcomplete" },
  { "name" = "grpcio" },
  { "name" = "types-grpcio" },
  { "name" = "pyserial" },
  { "name" = "types-pyserial" },
  { "name" = "folium" },
  { "name" = "structlog" },
  { "name" = "deepspeed" },
  { "name" = "openexr" },
  { "name" = "nose" },
  { "name" = "shortuuid" },
  { "name" = "openpifpaf" },
  { "name" = "pyrender" },
  { "name" = "backoff" },
  { "name" = "nbformat" },
  { "name" = "emoji" },
  { "name" = "mpmath" },
  { "name" = "ldap3" },
  { "name" = "types-ldap3" },
  { "name" = "typing-inspect" },
  { "name" = "astroid" },
  { "name" = "pandera" },
  { "name" = "astunparse" },
  { "name" = "xmltodict" },
  { "name" = "types-xmltodict" },
  { "name" = "pyproj" },
  { "name" = "aiogoogle" },
  { "name" = "pyquaternion" },
  { "name" = "sh" },
  { "name" = "nevergrad" },
  { "name" = "simple-parsing" },
  { "name" = "aiosqlite" },
  { "name" = "Deprecated" },
  { "name" = "types-Deprecated" },
  { "name" = "msgpack-numpy" },
  { "name" = "chevron" },
  { "name" = "types-chevron" },
  { "name" = "levenshtein" },
  { "name" = "toml" },
  { "name" = "types-toml" },
  { "name" = "json-tricks" },
  { "name" = "websockets" },
  { "name" = "geopandas" },
  { "name" = "types-geopandas" },
  { "name" = "jsonpath-rw" },
  { "name" = "dash" },
  { "name" = "click-option-group" },
  { "name" = "ujson1" },
  { "name" = "pystache" },
  { "name" = "dnspython" },
  { "name" = "pyjwt" },
  { "name" = "rawpy" },
  { "name" = "beautifulsoup4" },
  { "name" = "k-diffusion" },
  { "name" = "pydantic" },
  { "name" = "flash-attn" },
  { "name" = "pudb" },
  { "name" = "xlsxwriter" },
  { "name" = "semver" },
]
