# Curated list of PyPI projects to analyze.

projects = [
  { "name" = "numpy", "exclude" = ["numpy/typing/tests/**"] },
  { "name" = "scipy-stubs" },
  { "name" = "pandas" },
  { "name" = "pandas-stubs" },
  { "name" = "narhwals" },
  { "name" = "optype" },
]
