[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"

[project]
name = "typestats"
version = "0.1.0"
description = "Type annotation coverage statistics for Python packages"
readme = "README.md"
authors = [
  { name = "Joren Hammudoglu", email = "jhammudoglu@gmail.com" },
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
requires-python = ">=3.12"
dependencies = [
  "mainpy>=1.5,<2", # like `if __name__ == "__main__": ...` but Pythonic
  "tyro>=1.0.10", # like argparse but Pythonic
  "anyio>=4.12.1,<5", # like asyncio but with a decent API (asyncio is a mess)
  "libcst>=1.8.6,<2", # like ast but preservers comments/formatting and other goodies
  "pydantic>=2.12.5",
  "ruff>=0.15.7",
]

[project.scripts]
typestats = "typestats:__main__.app"

[dependency-groups]
site = [
  "typestats-site",
]
test = [
  "typestats",
  "pytest>=9.0.2",
  "pytest-httpx>=0.36.0,<1",
]
dev = [
  { include-group = "site" },
  { include-group = "test" },
  "dprint-py>=0.52.0.0",
  "pyrefly==0.57.1",
  "uvloop>=0.22.1,<1; sys_platform != 'win32'",
  "watchfiles>=1.1.1,<2",
]

[tool.uv.sources]
typestats-site = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

# pytest

[tool.pytest]
minversion = "9.0"
testpaths = ["src", "tests"]
addopts = ["-ra", "--doctest-modules", "--ignore=tests/fixtures"]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL", "ELLIPSIS"]
filterwarnings = ["error"]
log_level = "INFO"
strict = true

# pyrefly

[tool.pyrefly]
project-excludes = ["tests/fixtures/**"]
enabled-ignores = ["pyrefly"]

[tool.pyrefly.errors]
implicit-abstract-class = "error"
implicit-any = "error"
implicitly-defined-attribute = "error"
missing-override-decorator = "error"
missing-source = "ignore"
not-required-key-access = "error"
open-unpacking = "error"
unannotated-attribute = "error"
unannotated-parameter = "error"
unannotated-return = "error"
untyped-import = "error"
unused-ignore = "error"
variance-mismatch = "error"

# (based)pyright

[tool.pyright]
ignore = [".venv", "tests/fixtures/**"]
stubPath = "."
pythonPlatform = "All"
typeCheckingMode = "strict"
deprecateTypingAliases = true
enableReachabilityAnalysis = false
enableTypeIgnoreComments = false
reportImplicitOverride = true
reportImportCycles = true
reportUnnecessaryComparison = false
reportUnnecessaryTypeIgnoreComment = true
reportPrivateUsage = false

# ruff

[tool.ruff]
src = [
  "src",
  "tests",
  "packages/typestats-site/src",
  "packages/typestats-site/tests",
]
extend-exclude = [
  ".cache",
  ".pytest_cache",
  "tests/fixtures",
]
force-exclude = true
show-fixes = true
preview = true

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN401", # flake8-annotations - any-type
  "COM812", # missing-trailing-comma - conflicts with formatter
  "S101", # flake8-bandit - assert
  "S404", # flake8-bandit - suspicious-subprocess-import
  "FBT", # flake8-boolean-trap
  "CPY", # flake8-copyright
  "FIX", # flake8-fixme
  "TD003", # flake8-todos - missing-todo-link
  "D", # pydocstyle
  "DOC201", # pydoclint - docstring-missing-returns
  "TRY003", # tryceratops - raise-vanilla-args
  "RUF067", # ruff - non-empty-init-module
]

[tool.ruff.lint.per-file-ignores]
"packages/typestats-site/tests/**" = [
  "PLC2701", # pylint - import-private-name
  "PLR6301", # pylint - no-self-use
]

[tool.ruff.lint.pylint]
allow-magic-value-types = ["int", "str"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]
