name: Collect

on:
  schedule:
    # daily at 06:00 UTC
    - cron: "0 6 * * *"
  push:
    branches: [main]
    paths: [projects.toml]
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: collect
  cancel-in-progress: false

jobs:
  collect:
    if: >-
      github.event_name != 'pull_request'
      || (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'cmd: recollect'))
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: reports
    steps:
      - name: checkout main
        uses: actions/checkout@v6.0.2

      - name: checkout data
        uses: actions/checkout@v6.0.2
        with:
          ref: data
          path: _data

      - uses: astral-sh/setup-uv@v7.3.0
        with:
          python-version: "3.14t"

      - name: collect type-coverage data
        run: >-
          uv run -m typestats collect --data-dir _data/reports
          ${{ github.event_name == 'pull_request' && '--clean' || '' }}

      - name: build dashboard index
        run: uv run -m typestats dashboard --data-dir _data/reports --site-dir _data/site

      - name: Commit and push new data
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: reports/ site/
          commit: --signoff
          cwd: _data
          default_author: github_actions
          message: "Update type-coverage data"
