name: Recollect

on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: collect
  cancel-in-progress: false

jobs:
  recollect:
    name: recollect
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write # push collected data to the data branch
    environment: reports
    steps:
      - name: free disk space
        run: |
          sudo rm -rf /usr/lib/jvm /usr/share/dotnet /usr/share/swift /usr/local/.ghcup /usr/local/lib/android /opt/ghc || true
          docker system prune -af || true
          docker builder prune -af || true
          df -h /

      - name: checkout main
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          persist-credentials: false

      - name: checkout data
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: data
          path: _data
          persist-credentials: true

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14t"

      - name: recollect type-coverage data
        run: >-
          uv run -m typestats_site collect
          --data-dir _data/reports
          --clean
          --backfill-limit 1000

      - name: Commit and push new data
        working-directory: _data
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add reports/
          git diff --staged --quiet && exit 0
          git commit --signoff -m 'Recollect type-coverage data'
          git push
